#!/usr/bin/env python

cities = [
"Aberdeen",
"Abilene",
"Ada",
"Agat",
"Agawam",
"Agoura Hills",
"Aguadilla",
"Akron",
"Alameda",
"Alamogordo",
"Albany",
"Albuquerque",
"Alexandria",
"Alhambra",
"Aliquippa",
"Aliso Viejo",
"Allentown",
"Alpharetta",
"Altoona",
"Ames",
"Amesbury",
"Anaconda",
"Anaheim",
"Anchorage",
"Anderson",
"Ann Arbor",
"Annapolis",
"Ansonia",
"Apple Valley",
"Appleton",
"Arcadia",
"Ardmore",
"Areceibo",
"Arlington",
"Artesia",
"Arvada",
"Asbury Park",
"Asheville",
"Ashland",
"Aspen",
"Astoria",
"Athens",
"Atlanta",
"Atlantic City",
"Attleboro",
"Atwater",
"Auburn",
"Auburn Hills",
"Augusta",
"Aurora",
"Austin",
"Avalon",
"Azusa",
"Bakersfield",
"Baldwin Park",
"Baltimore",
"Bandera",
"Bandon",
"Bangor",
"Barre",
"Barrow",
"Bartlesville",
"Basin",
"Batavia",
"Baton Rouge",
"Battle Creek",
"Bay City",
"Bay St. Louis",
"Bayamon",
"Baytown",
"Beacon",
"Beaumont",
"Beaver Falls",
"Beckley",
"Bell",
"Bell Gardens",
"Belleville",
"Bellflower",
"Bellingham",
"Beloit",
"Belpre",
"Bend",
"Benton Harbor",
"Bentonville",
"Berkeley",
"Berlin",
"Bessemer",
"Bethany",
"Bethlehem",
"Beverly",
"Beverly Hills",
"Biddeford",
"Billings",
"Biloxi",
"Binghamton",
"Birmingham",
"Bismarck",
"Blacksburg",
"Bloomington",
"Blythe",
"Boise",
"Bossier City",
"Boston",
"Boulder",
"Boulder City",
"Boulder Junction",
"Bowie",
"Bowling Green",
"Bozeman",
"Bradbury",
"Bradford",
"Branson",
"Brea",
"Bremerton",
"Bridgeport",
"Brigham City",
"Bristol",
"Brockton",
"Broken Arrow",
"Brookfield",
"Brookings",
"Brooklyn Park",
"Brown Deer",
"Brownsville",
"Brunswick",
"Buena Park",
"Buffalo",
"Burbank",
"Burlingame",
"Burlington",
"Butler",
"Butte",
"Caguas",
"Cairo",
"Calabasas",
"Calumet City",
"Cambridge",
"Camden",
"Canandaigua",
"Canton",
"Cape Coral",
"Cape Girardeau",
"Cape May",
"Carbondale",
"Carolina",
"Carrollton",
"Carson",
"Carson City",
"Cary",
"Casper",
"Catskill",
"Cedar City",
"Cedar Falls",
"Cedar Rapids",
"Cedarburg",
"Centennial",
"Cerritos",
"Champaign",
"Chandler",
"Charleston",
"Charleston",
"Charlotte",
"Charlotte Amalie",
"Charlottesville",
"Chattanooga",
"Chelsea",
"Chesapeake",
"Chester",
"Cheyenne",
"Chicago",
"Chicago Heights",
"Chickasha",
"Chico",
"Chicopee",
"Chino",
"Chino Hills",
"Christiansted",
"Chula Vista",
"Cicero",
"Cincinnati",
"Citrus Heights",
"City of Industry",
"Clairton",
"Claremont",
"Claremore",
"Clarksburg",
"Clarksville",
"Clearwater",
"Clemson",
"Cleveland",
"Clovis",
"Coatesville",
"Cody",
"Cohoes",
"College Park",
"College Station",
"Colorado Springs",
"Columbia",
"Columbia",
"Columbus",
"Columbus",
"Commerce",
"Compton",
"Concord",
"Concord",
"Connellsville",
"Coos Bay",
"Coral Springs",
"Corinth",
"Corona",
"Corpus Christi",
"Corry",
"Cortland",
"Corvallis",
"Costa Mesa",
"Council Bluffs",
"Covina",
"Covington",
"Cranston",
"Crown Point",
"Cruz Bay",
"Cudahy",
"Culver City",
"Cumberland",
"Cypress",
"Dallas",
"Dalton",
"Daly City",
"Dana Point",
"Danbury",
"Danville",
"Darlington",
"Davenport",
"Davis",
"Dayton",
"Deadwood",
"Dearborn",
"Decatur",
"DeKalb",
"Del Rio",
"Delta Junction",
"Denver",
"Derby",
"Des Moines",
"Detroit",
"Diamond Bar",
"Dickinson",
"Dixon",
"Dodge City",
"Dothan",
"Douglas",
"Dover",
"Dover",
"Downey",
"Duarte",
"DuBois",
"Dubuque",
"Duluth",
"Duncan",
"Dunkirk",
"Duquesne",
"Durango",
"Durant",
"Durham",
"East Hartford",
"East Lansing",
"East Rutherford",
"East St. Louis",
"Easthampton",
"Easton",
"Eatontown",
"Eau Claire",
"Eden Prairie",
"Edina",
"Edmond",
"Effingham",
"Egg Harbor",
"El Cerrito",
"El Monte",
"El Paso",
"El Segundo",
"Elizabeth City",
"Elkhart",
"Elko",
"Elmira",
"Elsmere",
"Enfield",
"Enid",
"Ephraim",
"Erie",
"Escondido",
"Eufaula",
"Eugene",
"Eureka",
"Evanston",
"Evansville",
"Everett",
"Fairbanks",
"Fairfax",
"Fairfield",
"Fairmont",
"Fajardo",
"Fall River",
"Fallon",
"Falls Church",
"Fargo",
"Farmer City",
"Farmington",
"Farrell",
"Fayetteville",
"Fernley",
"Fitchburg",
"Flagstaff",
"Flint",
"Florence",
"Fond du Lac",
"Fontana",
"Forest Lake",
"Forrest City",
"Fort Collins",
"Fort Dodge",
"Fort Lauderdale",
"Fort Smith",
"Fort Wayne",
"Fort Worth",
"Fountain Valley",
"Frankfort",
"Franklin",
"Frederick",
"Fredericksburg",
"Frederiksted",
"Fremont",
"Fresno",
"Frisco",
"Fullerton",
"Fulton",
"Gadsden",
"Gainesville",
"Gaithersburg",
"Galesburg",
"Gallup",
"Galveston",
"Garden Grove",
"Gardena",
"Gardner",
"Garland",
"Gary",
"Gastonia",
"Gatlinburg",
"Geneva",
"Georgetown",
"Gettysburg",
"Gilbert",
"Gilette",
"Glen Cove",
"Glendale",
"Glendora",
"Glens Falls",
"Gloucester",
"Gloversville",
"Gold Beach",
"Goose Creek",
"Grafton",
"Grambling",
"Grand Forks",
"Grand Island",
"Grand Junction",
"Grand Rapids",
"Grass Valley",
"Great Falls",
"Green Bay",
"Green River",
"Greenfield",
"Greensboro",
"Greensburg",
"Greenville",
"Guayama",
"Guayanilla",
"Gulfport",
"Guthrie",
"Hackensack",
"Hagerstown",
"Half Moon Bay",
"Hamilton",
"Hammond",
"Hampton",
"Hanahan",
"Hannibal",
"Harrisburg",
"Hartford",
"Hartford",
"Hartland",
"Hastings",
"Hattiesburg",
"Haverhill",
"Hawaiian Gardens",
"Hawthorne",
"Hayward",
"Hazleton",
"Healdsburg",
"Helena",
"Henderson",
"Hermitage",
"Hermosa Beach",
"Hialeah",
"Hickory",
"Hidden Hills",
"High Point",
"Highland Park",
"Hilo",
"Hoboken",
"Hollister",
"Hollywood",
"Holyoke",
"Homer",
"Honolulu",
"Hoover",
"Hope",
"Hopkinsville",
"Hornell",
"Hot Springs",
"Houma",
"Houston",
"Hudson",
"Huntington",
"Huntington Beach",
"Huntington Park",
"Huntsville",
"Hutchinson",
"Idabel",
"Idaho Falls",
"Idaho Springs",
"Independence",
"Indianapolis",
"Indio",
"Inglewood",
"International Falls",
"Iowa City",
"Irvine",
"Irving",
"Irwindale",
"Isle of Palms",
"Ithaca",
"Jackson",
"Jackson",
"Jacksonville",
"Jamestown",
"Janesville",
"Jeannette",
"Jefferson City",
"Jeffersontown",
"Jeffersonville",
"Jenks",
"Jersey City",
"Johnson City",
"Johnstown",
"Joliet",
"Jonesboro",
"Joplin",
"Jordan Valley",
"Juneau",
"Kahului",
"Kalamazoo",
"Kalispell",
"Kankakee",
"Kansas City",
"Kearney",
"Kearns",
"Keene",
"Kemmerer",
"Kenner",
"Kennesaw",
"Kennewick",
"Kenosha",
"Kent",
"Ketchikan",
"Kettering",
"Kingsport",
"Kingston",
"Klamath Falls",
"Knoxville",
"Kokomo",
"Kona",
"La Crosse",
"La Habra",
"La Habra Heights",
"La Jolla",
"La Mirada",
"La Palma",
"La Puente",
"La Verne",
"Laconia",
"Lafayette",
"LaGrange",
"Laguna Beach",
"Laguna Hills",
"Laguna Niguel",
"Laguna Woods",
"Lahaina",
"Lake Charles",
"Lake Forest",
"Lakeland",
"Lakewood",
"Lancaster",
"Lander",
"Lansing",
"Laramie",
"Laredo",
"Las Cruces",
"Las Vegas",
"Latrobe",
"Laughlin",
"Laurel",
"Lawndale",
"Lawrence",
"Lawrenceville",
"Lawton",
"Layton",
"Lebanon",
"Leominster",
"Lewiston",
"Lexington",
"Liberal",
"Lima",
"Lincoln",
"Little Falls",
"Little Rock",
"Littleton",
"Livonia",
"Lock Haven",
"Lockport",
"Lodi",
"Logan",
"Lomita",
"Long Beach",
"Longview",
"Los Alamitos",
"Los Angeles",
"Loudon",
"Louisville",
"Lowell",
"Lower Burrell",
"Lubbock",
"Lufkin",
"Lynchburg",
"Lynn",
"Lynwood",
"Macomb",
"Macon",
"Madison",
"Malden",
"Malibu",
"Manassas",
"Manassas Park",
"Manchester",
"Mandan",
"Manhattan",
"Manhattan Beach",
"Manitowoc",
"Mankato",
"Marietta",
"Marlborough",
"Marquette",
"Marshall",
"Marshfield",
"Martinsburg",
"Mason City",
"Maywood",
"McAlester",
"McAllen",
"McKeesport",
"Meadville",
"Mechanicville",
"Medford",
"Melrose",
"Memphis",
"Menomonee Falls",
"Mentor",
"Mequon",
"Merced",
"Meriden",
"Meridian",
"Merizo",
"Mesa",
"Mesquite",
"Methuen",
"Miami",
"Miami Beach",
"Miami Gardens",
"Michigan City",
"Middlebury",
"Middletown",
"Midland",
"Midwest City",
"Milford",
"Milwaukee",
"Minneapolis",
"Minnetonka",
"Minot",
"Mission Viejo",
"Missoula",
"Mobile",
"Modesto",
"Moline",
"Monongahela",
"Monroe",
"Monrovia",
"Montebello",
"Monterey",
"Monterey Park",
"Montgomery",
"Montpelier",
"Moore",
"Moorhead",
"Moraga",
"Moreno Valley",
"Morgan City",
"Morgantown",
"Morrison",
"Moscow",
"Moultrie",
"Mount Pleasant",
"Mount Vernon",
"Muncie",
"Murfreesboro",
"Murray",
"Murrieta",
"Muskegon",
"Muskogee",
"Myrtle Beach",
"Nacogdoches",
"Nampa",
"Nanticoke",
"Naperville",
"Narragansett",
"Nashua",
"Nashville",
"Natchez",
"Natchitoches",
"Needham",
"Nenana",
"Nevada City",
"New Albany",
"New Bedford",
"New Britain",
"New Brunswick",
"New Castle",
"New Haven",
"New Iberia",
"New Kensington",
"New London",
"New Madrid",
"New Orleans",
"New Rochelle",
"New York",
"Newark",
"Newburgh",
"Newburyport",
"Newcastle",
"Newport",
"Newport Beach",
"Newport News",
"Newton",
"Niagara Falls",
"Nichols Hills",
"Nogales",
"Nome",
"Norfolk",
"Normal",
"Norman",
"North Adams",
"North Charleston",
"North Chicago",
"North Las Vegas",
"North Little Rock",
"North Platte",
"North Pole",
"North Tonawanda",
"Northampton",
"Norton",
"Norwalk",
"Norwich",
"Oak Ridge",
"Oakland",
"Ocean City",
"Odessa",
"Ogden",
"Ogdensburg",
"Oil City",
"Oklahoma City",
"Olean",
"Olympia",
"Omaha",
"Oneida",
"Oneonta",
"Ontario",
"Opelousas",
"Orange",
"Orangeburg",
"Orem",
"Orlando",
"Oro Valley",
"Oshkosh",
"Oswego",
"Overland Park",
"Owensboro",
"Oxford",
"Oxnard",
"Paducah",
"Palm Springs",
"Palmdale",
"Palo Alto",
"Palos Verdes Estates",
"Paramount",
"Parker",
"Parkersburg",
"Parma",
"Pasadena",
"Pascagoula",
"Pasco",
"Pass Christian",
"Passaic",
"Paterson",
"Pawtucket",
"Peabody",
"Peekskill",
"Pembroke Pines",
"Pendleton",
"Peoria",
"Perth Amboy",
"Peru",
"Phenix City",
"Philadelphia",
"Phoenix",
"Pico Rivera",
"Pierre",
"Pine Bluff",
"Pittsburgh",
"Pittsfield",
"Pittston",
"Placentia",
"Plainfield",
"Plano",
"Plantation",
"Plattsburgh",
"Plymouth",
"Pocatello",
"Pomona",
"Ponce",
"Port Arthur",
"Port Huron",
"Port Jervis",
"Port Orford",
"Port St. Lucie",
"Port Washington",
"Portland",
"Portsmouth",
"Pottsville",
"Poughkeepsie",
"Powell",
"Prescott",
"Princeton",
"Providence",
"Provo",
"Pueblo",
"Pulaski",
"Pullman",
"Quincy",
"Racine",
"Radford",
"Raleigh",
"Rancho Cordova",
"Rancho Cucamonga",
"Rancho Palos Verdes",
"Rancho Santa Margarita",
"Rapid City",
"Rawlins",
"Reading",
"Redding",
"Redlands",
"Redondo Beach",
"Reedsport",
"Rehoboth Beach",
"Reno",
"Rensselaer",
"Revere",
"Rhinelander",
"Rialto",
"Richland",
"Richmond",
"Richmond",
"Riverside",
"Riverton",
"Roanoke",
"Rochester",
"Rock Island",
"Rock Springs",
"Rockford",
"Rockville",
"Rocky Mount",
"Rohnert Park",
"Rolla",
"Rolling Hills",
"Rolling Hills Estates",
"Rome",
"Rosemead",
"Roseville",
"Roswell",
"Ruston",
"Rutland",
"Rye",
"Sacramento",
"Saginaw",
"Saint Albans",
"Saint Cloud",
"Saint Joseph",
"Saint Louis",
"Saint Paul",
"Saipan",
"Salem",
"Salem",
"Salinas",
"Salisbury",
"Salt Lake City",
"San Angelo",
"San Antonio",
"San Bernardino",
"San Clemente",
"San Diego",
"San Dimas",
"San Fernando",
"San Francisco",
"San Gabriel",
"San Jose",
"San Juan",
"San Juan Capistrano",
"San Luis Obispo",
"San Marino",
"San Mateo",
"San Rafael",
"Sandpoint",
"Sandy",
"Sandy Springs",
"Sanford",
"Santa Ana",
"Santa Barbara",
"Santa Clara",
"Santa Clarita",
"Santa Cruz",
"Santa Fe",
"Santa Fe Springs",
"Santa Monica",
"Santa Rosa",
"Saratoga Springs",
"Saukville",
"Sault Ste. Marie",
"Savannah",
"Scarborough",
"Schaumburg",
"Schenectady",
"Scottsbluff",
"Scottsdale",
"Scranton",
"Seaford",
"Seal Beach",
"Seattle",
"Sedalia",
"Selma",
"Seward",
"Shamokin",
"Sharon",
"Shawnee",
"Sheboygan",
"Shelton",
"Sheridan",
"Sherrill",
"Shreveport",
"Sierra Madre",
"Sierra Vista",
"Signal Hill",
"Simi Valley",
"Sioux City",
"Sioux Falls",
"Sister Bay",
"Sitka",
"Slidell",
"Somersworth",
"Somerville",
"Sonoma",
"South Bend",
"South Burlington",
"South El Monte",
"South Gate",
"South Pasadena",
"South Portland",
"Spartanburg",
"Spokane",
"Spokane Valley",
"Springdale",
"Springfield",
"Springfield",
"St. George",
"St. Marys",
"St. Petersburg",
"Stafford",
"Stamford",
"Stanton",
"Starkville",
"Statesboro",
"Staunton",
"Steubenville",
"Stevens Point",
"Stillwater",
"Stockton",
"Sturgis",
"Suffolk",
"Sugar Land",
"Sun Valley",
"Sunbury",
"Sunnyvale",
"Superior",
"Sutter Creek",
"Syracuse",
"Tacoma",
"Tallahassee",
"Tampa",
"Tamuning",
"Taunton",
"Taylorsville",
"Temecula",
"Tempe",
"Temple City",
"Terre Haute",
"Texarkana",
"Texas City",
"The Dalles",
"Thibodaux",
"Thiensville",
"Thomasville",
"Thousand Oaks",
"Titusville",
"Tok",
"Toledo",
"Tonawanda",
"Topeka",
"Torrance",
"Torrington",
"Trenton",
"Troy",
"Truth or Consequences",
"Tucson",
"Tulsa",
"Tupelo",
"Turlock",
"Tuscaloosa",
"Tustin",
"Twin Falls",
"Two Rivers",
"Tyler",
"Union City",
"Uniontown",
"Urbana",
"Utica",
"Vacaville",
"Vail",
"Valdez",
"Valdosta",
"Valencia",
"Vallejo",
"Valparaiso",
"Vancouver",
"Ventura",
"Vergennes",
"Vermillion",
"Vernon",
"Vicksburg",
"Victoria",
"Villa Park",
"Vincennes",
"Vineland",
"Virginia Beach",
"Visalia",
"Waco",
"Wahoo",
"Walla Walla",
"Walnut",
"Waltham",
"Warner Robins",
"Warren",
"Warwick",
"Washington",
"Waterbury",
"Waterloo",
"Watertown",
"Watervliet",
"Waukegan",
"Wausau",
"Waycross",
"Webster Groves",
"Weirton",
"West Allis",
"West Bend",
"West Covina",
"West Hartford",
"West Haven",
"West Hollywood",
"West Jordan",
"West Lafayette",
"West Memphis",
"West Palm Beach",
"West Sacramento",
"West Springfield",
"West Valley City",
"West Warwick",
"Westfield",
"Westlake Village",
"Westminster",
"Weymouth",
"Wheaton",
"Wheeling",
"White Plains",
"Whittier",
"Wichita",
"Wichita Falls",
"Wilkes-Barre",
"Williamsburg",
"Williamsport",
"Williston",
"Wilmington",
"Wilson",
"Winnemucca",
"Winooski",
"Winston-Salem",
"Wisconsin Dells",
"Wisconsin Rapids",
"Woburn",
"Woodruff",
"Woodward",
"Woonsocket",
"Worcester",
"Worland",
"Wynne",
"Yakima",
"Yazoo City",
"Yigo",
"Yonkers",
"Yorba Linda",
"York",
"Youngstown",
"Ypsilanti",
"Yukon",
"Yuma",
"Zanesville"
]

counties = [
("Aberdeenshire","ABD","Scotland"),
("Anglesey","AGY","Wales"),
("Alderney","ALD","Channel Islands"),
("Angus","ANS","Scotland"),
("Co. Antrim","ANT","Northern Ireland"),
("Argyllshire","ARL","Scotland"),
("Co. Armagh","ARM","Northern Ireland"),
("Avon","AVN","England"),
("Ayrshire","AYR","Scotland"),
("Banffshire","BAN","Scotland"),
("Bedfordshire","BDF","England"),
("Berwickshire","BEW","Scotland"),
("Buckinghamshire","BKM","England"),
("Borders","BOR","Scotland"),
("Breconshire","BRE","Wales"),
("Berkshire","BRK","England"),
("Bute","BUT","Scotland"),
("Caernarvonshire","CAE","Wales"),
("Caithness","CAI","Scotland"),
("Cambridgeshire","CAM","England"),
("Co. Carlow","CAR","Ireland"),
("Co. Cavan","CAV","Ireland"),
("Central","CEN","Scotland"),
("Cardiganshire","CGN","Wales"),
("Cheshire","CHS","England"),
("Co. Clare","CLA","Ireland"),
("Clackmannanshire","CLK","Scotland"),
("Cleveland","CLV","England"),
("Cumbria","CMA","England"),
("Carmarthenshire","CMN","Wales"),
("Cornwall","CON","England"),
("Co. Cork","COR","Ireland"),
("Cumberland","CUL","England"),
("Clwyd","CWD","Wales"),
("Derbyshire","DBY","England"),
("Denbighshire","DEN","Wales"),
("Devon","DEV","England"),
("Dyfed","DFD","Wales"),
("Dumfries-shire","DFS","Scotland"),
("Dumfries and Galloway","DGY","Scotland"),
("Dunbartonshire","DNB","Scotland"),
("Co. Donegal","DON","Ireland"),
("Dorset","DOR","England"),
("Co. Down","DOW","Northern Ireland"),
("Co. Dublin","DUB","Ireland"),
("Co. Durham","DUR","England"),
("East Lothian","ELN","Scotland"),
("East Riding of Yorkshire","ERY","England"),
("Essex","ESS","England"),
("Co. Fermanagh","FER","Northern Ireland"),
("Fife","FIF","Scotland"),
("Flintshire","FLN","Wales"),
("Co. Galway","GAL","Ireland"),
("Glamorgan","GLA","Wales"),
("Gloucestershire","GLS","England"),
("Grampian","GMP","Scotland"),
("Gwent","GNT","Wales"),
("Guernsey","GSY","Channel Islands"),
("Greater Manchester","GTM","England"),
("Gwynedd","GWN","Wales"),
("Hampshire","HAM","England"),
("Herefordshire","HEF","England"),
("Highland","HLD","Scotland"),
("Hertfordshire","HRT","England"),
("Humberside","HUM","England"),
("Huntingdonshire","HUN","England"),
("Hereford and Worcester","HWR","England"),
("Inverness-shire","INV","Scotland"),
("Isle of Wight","IOW","England"),
("Jersey","JSY","Channel Islands"),
("Kincardineshire","KCD","Scotland"),
("Kent","KEN","England"),
("Co. Kerry","KER","Ireland"),
("Co. Kildare","KID","Ireland"),
("Co. Kilkenny","KIK","Ireland"),
("Kirkcudbrightshire","KKD","Scotland"),
("Kinross-shire","KRS","Scotland"),
("Lancashire","LAN","England"),
("Co. Londonderry","LDY","Northern Ireland"),
("Leicestershire","LEI","England"),
("Co. Leitrim","LET","Ireland"),
("Co. Laois","LEX","Ireland"),
("Co. Limerick","LIM","Ireland"),
("Lincolnshire","LIN","England"),
("Lanarkshire","LKS","Scotland"),
("London","LND","England"),
("Co. Longford","LOG","Ireland"),
("Co. Louth","LOU","Ireland"),
("Lothian","LTN","Scotland"),
("Co. Mayo","MAY","Ireland"),
("Middlesex","MDX","England"),
("Co. Meath","MEA","Ireland"),
("Merionethshire","MER","Wales"),
("Mid Glamorgan","MGM","Wales"),
("Montgomeryshire","MGY","Wales"),
("Midlothian","MLN","Scotland"),
("Co. Monaghan","MOG","Ireland"),
("Monmouthshire","MON","Wales"),
("Morayshire","MOR","Scotland"),
("Merseyside","MSY","England"),
("Nairn","NAI","Scotland"),
("Northumberland","NBL","England"),
("Norfolk","NFK","England"),
("North Riding of Yorkshire","NRY","England"),
("Northamptonshire","NTH","England"),
("Nottinghamshire","NTT","England"),
("North Yorkshire","NYK","England"),
("Co. Offaly","OFF","Ireland"),
("Orkney","OKI","Scotland"),
("Oxfordshire","OXF","England"),
("Peebles-shire","PEE","Scotland"),
("Pembrokeshire","PEM","Wales"),
("Perth","PER","Scotland"),
("Powys","POW","Wales"),
("Radnorshire","RAD","Wales"),
("Renfrewshire","RFW","Scotland"),
("Ross and Cromarty","ROC","Scotland"),
("Co. Roscommon","ROS","Ireland"),
("Roxburghshire","ROX","Scotland"),
("Rutland","RUT","England"),
("Shropshire","SAL","England"),
("Selkirkshire","SEL","Scotland"),
("Suffolk","SFK","England"),
("South Glamorgan","SGM","Wales"),
("Shetland","SHI","Scotland"),
("Co. Sligo","SLI","Ireland"),
("Somerset","SOM","England"),
("Sark","SRK","Channel Islands"),
("Surrey","SRY","England"),
("Sussex","SSX","England"),
("Strathclyde","STD","Scotland"),
("Stirlingshire","STI","Scotland"),
("Staffordshire","STS","England"),
("Sutherland","SUT","Scotland"),
("East Sussex","SXE","England"),
("West Sussex","SXW","England"),
("South Yorkshire","SYK","England"),
("Tayside","TAY","Scotland"),
("Co. Tipperary","TIP","Ireland"),
("Tyne and Wear","TWR","England"),
("Co. Tyrone","TYR","Northern Ireland"),
("Warwickshire","WAR","England"),
("Co. Waterford","WAT","Ireland"),
("Co. Westmeath","WEM","Ireland"),
("Westmorland","WES","England"),
("Co. Wexford","WEX","Ireland"),
("West Glamorgan","WGM","Wales"),
("Co. Wicklow","WIC","Ireland"),
("Wigtownshire","WIG","Scotland"),
("Wiltshire","WIL","England"),
("Western Isles","WIS","Scotland"),
("West Lothian","WLN","Scotland"),
("West Midlands","WMD","England"),
("Worcestershire","WOR","England"),
("West Riding of Yorkshire","WRY","England"),
("West Yorkshire","WYK","England"),
("Yorkshire","YKS","England")
]

countries = [
"Afghanistan",
"Albania",
"Algeria",
"American Samoa",
"Andorra",
"Angola",
"Anguilla",
"Antarctica",
"Antigua and Barbuda",
"Argentina",
"Armenia",
"Aruba",
"Australia",
"Austria",
"Azerbaijan",
"Bahamas",
"Bahrain",
"Bangladesh",
"Barbados",
"Belarus",
"Belgium",
"Belize",
"Benin",
"Bermuda",
"Bhutan",
"Bolivia",
"Bosnia and Herzegovina",
"Botswana",
"Bouvet Island",
"Brazil",
"British Indian Ocean Territory",
"Brunei Darussalam",
"Bulgaria",
"Burkina Faso",
"Burundi",
"Cambodia",
"Cameroon",
"Canada",
"Cape Verde",
"Cayman Islands",
"Central African Republic",
"Chad",
"Chile",
"China",
"Christmas Island",
"Cocos (Keeling) Islands",
"Colombia",
"Comoros",
"Congo",
"Cook Islands",
"Costa Rica",
"Croatia",
"Cuba",
"Cyprus",
"Czech Republic",
"Denmark",
"Djibouti",
"Dominica",
"Dominican Republic",
"Ecuador",
"Egypt",
"El Salvador",
"Equatorial Guinea",
"Eritrea",
"Estonia",
"Ethiopia",
"Falkland Islands (Malvinas)",
"Faroe Islands",
"Fiji",
"Finland",
"France",
"French Guiana",
"French Polynesia",
"French Southern Territories",
"Gabon",
"Gambia",
"Georgia",
"Germany",
"Ghana",
"Gibraltar",
"Greece",
"Greenland",
"Grenada",
"Guadeloupe",
"Guam",
"Guatemala",
"Guinea",
"Guinea-bissau",
"Guyana",
"Haiti",
"Heard Island and Mcdonald Islands",
"Holy See (Vatican City State)",
"Honduras",
"Hong Kong",
"Hungary",
"Iceland",
"India",
"Indonesia",
"Iran, Islamic Republic of",
"Iraq",
"Ireland",
"Israel",
"Italy",
"Jamaica",
"Japan",
"Jordan",
"Kazakhstan",
"Kenya",
"Kiribati",
"Korea",
"Korea, Republic of",
"Kuwait",
"Kyrgyzstan",
"Latvia",
"Lebanon",
"Lesotho",
"Liberia",
"Libyan Arab Jamahiriya",
"Liechtenstein",
"Lithuania",
"Luxembourg",
"Macao",
"Macedonia",
"Madagascar",
"Malawi",
"Malaysia",
"Maldives",
"Mali",
"Malta",
"Marshall Islands",
"Martinique",
"Mauritania",
"Mauritius",
"Mayotte",
"Mexico",
"Micronesia",
"Moldova",
"Monaco",
"Mongolia",
"Montserrat",
"Morocco",
"Mozambique",
"Myanmar",
"Namibia",
"Nauru",
"Nepal",
"Netherlands",
"Netherlands Antilles",
"New Caledonia",
"New Zealand",
"Nicaragua",
"Niger",
"Nigeria",
"Niue",
"Norfolk Island",
"Northern Mariana Islands",
"Norway",
"Oman",
"Pakistan",
"Palau",
"Palestinian Territory, Occupied",
"Panama",
"Papua New Guinea",
"Paraguay",
"Peru",
"Philippines",
"Pitcairn",
"Poland",
"Portugal",
"Puerto Rico",
"Qatar",
"Reunion",
"Romania",
"Russian Federation",
"Rwanda",
"Saint Helena",
"Saint Kitts and Nevis",
"Saint Lucia",
"Saint Pierre and Miquelon",
"Saint Vincent and The Grenadines",
"Samoa",
"San Marino",
"Sao Tome and Principe",
"Saudi Arabia",
"Senegal",
"Serbia and Montenegro",
"Seychelles",
"Sierra Leone",
"Singapore",
"Slovakia",
"Slovenia",
"Solomon Islands",
"Somalia",
"South Africa",
"South Georgia and The South Sandwich Islands",
"Spain",
"Sri Lanka",
"Sudan",
"Suriname",
"Svalbard and Jan Mayen",
"Swaziland",
"Sweden",
"Switzerland",
"Syrian Arab Republic",
"Taiwan, Province of China",
"Tajikistan",
"Tanzania, United Republic of",
"Thailand",
"Timor-leste",
"Togo",
"Tokelau",
"Tonga",
"Trinidad and Tobago",
"Tunisia",
"Turkey",
"Turkmenistan",
"Turks and Caicos Islands",
"Tuvalu",
"Uganda",
"Ukraine",
"United Arab Emirates",
"United Kingdom",
"United States",
"United States Minor Outlying Islands",
"Uruguay",
"Uzbekistan",
"Vanuatu",
"Venezuela",
"Viet Nam",
"Virgin Islands, British",
"Virgin Islands, U.S.",
"Wallis and Futuna",
"Western Sahara",
"Yemen",
"Zambia",
"Zimbabwe"
]

first_names = [
("Aaron","male"),
("Abbot","male"),
("Abdul","male"),
("Abel","male"),
("Abigail","female"),
("Abra","female"),
("Abraham","male"),
("Acton","male"),
("Adam","male"),
("Adara","female"),
("Addison","male"),
("Adele","female"),
("Adena","female"),
("Adria","female"),
("Adrian","male"),
("Adrienne","female"),
("Ahmed","male"),
("Aidan","male"),
("Aiko","female"),
("Aileen","female"),
("Aimee","female"),
("Ainsley","female"),
("Akeem","male"),
("Aladdin","male"),
("Alan","male"),
("Alana","female"),
("Alden","male"),
("Alea","female"),
("Alec","male"),
("Alexa","female"),
("Alexander","male"),
("Alexandra","female"),
("Alexis","female"),
("Alfonso","male"),
("Alfreda","female"),
("Ali","male"),
("Alice","female"),
("Alika","female"),
("Aline","female"),
("Alisa","female"),
("Allegra","female"),
("Allen","male"),
("Allistair","male"),
("Alma","female"),
("Althea","female"),
("Alvin","male"),
("Alyssa","female"),
("Amal","male"),
("Amanda","female"),
("Amaya","female"),
("Amber","female"),
("Amela","female"),
("Amelia","female"),
("Amena","female"),
("Amery","male"),
("Amethyst","female"),
("Amir","male"),
("Amity","female"),
("Amos","male"),
("Amy","female"),
("Anastasia","female"),
("Andrew","male"),
("Angela","female"),
("Angelica","female"),
("Anika","female"),
("Anjolie","female"),
("Ann","female"),
("Anne","female"),
("Anthony","male"),
("Aphrodite","female"),
("April","female"),
("Aquila","male"),
("Arden","male"),
("Aretha","female"),
("Ariana","female"),
("Ariel","female"),
("Aristotle","male"),
("Armand","male"),
("Armando","male"),
("Arsenio","male"),
("Arthur","male"),
("Ashely","female"),
("Asher","male"),
("Ashton","male"),
("Aspen","female"),
("Astra","female"),
("Athena","female"),
("Aubrey","both"),
("Audra","female"),
("Audrey","female"),
("August","male"),
("Aurelia","female"),
("Aurora","female"),
("Austin","male"),
("Autumn","female"),
("Ava","female"),
("Avram","male"),
("Avye","female"),
("Axel","male"),
("Ayanna","female"),
("Azalia","female"),
("Baker","male"),
("Barbara","female"),
("Barclay","male"),
("Barrett","male"),
("Barry","male"),
("Basia","female"),
("Basil","male"),
("Baxter","male"),
("Beatrice","female"),
("Beau","male"),
("Beck","male"),
("Bell","female"),
("Belle","female"),
("Benedict","male"),
("Benjamin","male"),
("Berk","male"),
("Bernard","male"),
("Bert","male"),
("Bertha","female"),
("Bethany","female"),
("Beverly","female"),
("Bevis","male"),
("Bianca","female"),
("Blaine","both"),
("Blair","both"),
("Blake","male"),
("Blaze","male"),
("Blossom","female"),
("Blythe","female"),
("Bo","female"),
("Boris","male"),
("Bradley","male"),
("Brady","male"),
("Branden","male"),
("Brandon","male"),
("Breanna","female"),
("Bree","female"),
("Brenda","female"),
("Brendan","male"),
("Brenden","male"),
("Brenna","female"),
("Brennan","male"),
("Brent","male"),
("Brett","male"),
("Brian","male"),
("Brianna","female"),
("Briar","female"),
("Brielle","female"),
("Britanney","female"),
("Britanni","female"),
("Brittany","female"),
("Brock","male"),
("Brody","male"),
("Brooke","female"),
("Bruce","male"),
("Bruno","male"),
("Bryar","female"),
("Brynn","female"),
("Brynne","female"),
("Buckminster","male"),
("Buffy","female"),
("Burke","male"),
("Burton","male"),
("Byron","male"),
("Cade","male"),
("Cadman","male"),
("Caesar","male"),
("Cailin","female"),
("Cain","male"),
("Cairo","male"),
("Caldwell","male"),
("Caleb","male"),
("Calista","female"),
("Callie","female"),
("Callum","male"),
("Cally","female"),
("Calvin","male"),
("Camden","male"),
("Cameran","female"),
("Cameron","female"),
("Cameron","male"),
("Camilla","female"),
("Camille","female"),
("Candace","female"),
("Candice","female"),
("Cara","female"),
("Carissa","female"),
("Carl","male"),
("Carla","female"),
("Carlos","male"),
("Carly","female"),
("Carol","female"),
("Carolyn","female"),
("Carson","male"),
("Carter","male"),
("Caryn","female"),
("Casey","both"),
("Cassady","female"),
("Cassandra","female"),
("Cassidy","female"),
("Castor","male"),
("Catherine","female"),
("Cathleen","female"),
("Cecilia","female"),
("Cedric","male"),
("Celeste","female"),
("Chadwick","male"),
("Chaim","male"),
("Chancellor","male"),
("Chanda","female"),
("Chandler","male"),
("Chaney","male"),
("Channing","male"),
("Chantale","female"),
("Charde","female"),
("Charissa","female"),
("Charity","female"),
("Charles","male"),
("Charlotte","female"),
("Chase","male"),
("Chastity","female"),
("Chava","female"),
("Chelsea","female"),
("Cherokee","female"),
("Cheryl","female"),
("Chester","male"),
("Cheyenne","female"),
("Chiquita","female"),
("Chloe","female"),
("Christen","female"),
("Christian","male"),
("Christine","female"),
("Christopher","male"),
("Ciara","female"),
("Ciaran","male"),
("Claire","female"),
("Clare","female"),
("Clark","male"),
("Clarke","male"),
("Claudia","female"),
("Clayton","male"),
("Clementine","female"),
("Cleo","female"),
("Clinton","male"),
("Clio","female"),
("Coby","male"),
("Cody","male"),
("Colby","male"),
("Cole","male"),
("Colette","female"),
("Colin","male"),
("Colleen","female"),
("Colorado","male"),
("Colt","male"),
("Colton","male"),
("Conan","male"),
("Connor","male"),
("Constance","female"),
("Cooper","male"),
("Cora","female"),
("Courtney","female"),
("Craig","male"),
("Cruz","male"),
("Cullen","male"),
("Curran","male"),
("Cynthia","female"),
("Cyrus","male"),
("Dacey","female"),
("Dahlia","female"),
("Dai","female"),
("Dakota","both"),
("Dale","male"),
("Dalton","male"),
("Damian","male"),
("Damon","male"),
("Dana","female"),
("Dane","male"),
("Daniel","male"),
("Danielle","female"),
("Dante","male"),
("Daphne","female"),
("Daquan","male"),
("Dara","female"),
("Daria","female"),
("Darius","male"),
("Darrel","female"),
("Darryl","female"),
("Daryl","female"),
("David","male"),
("Davis","male"),
("Dawn","female"),
("Deacon","male"),
("Dean","male"),
("Deanna","female"),
("Deborah","female"),
("Debra","female"),
("Declan","male"),
("Deirdre","female"),
("Delilah","female"),
("Demetria","female"),
("Demetrius","male"),
("Denise","female"),
("Dennis","male"),
("Denton","male"),
("Derek","male"),
("Desirae","female"),
("Desiree","female"),
("Destiny","female"),
("Devin","male"),
("Dexter","male"),
("Diana","female"),
("Dieter","male"),
("Dillon","male"),
("Dolan","male"),
("Dominic","male"),
("Dominique","female"),
("Donna","female"),
("Donovan","male"),
("Dora","female"),
("Dorian","male"),
("Doris","female"),
("Dorothy","female"),
("Drake","male"),
("Drew","male"),
("Driscoll","male"),
("Duncan","male"),
("Dustin","male"),
("Dylan","male"),
("Eagan","male"),
("Eaton","male"),
("Ebony","female"),
("Echo","female"),
("Edan","male"),
("Eden","both"),
("Edward","male"),
("Elaine","female"),
("Eleanor","female"),
("Eliana","female"),
("Elijah","male"),
("Elizabeth","female"),
("Ella","female"),
("Elliott","male"),
("Elmo","male"),
("Elton","male"),
("Elvis","male"),
("Emerald","female"),
("Emerson","male"),
("Emery","male"),
("Emi","female"),
("Emily","female"),
("Emma","female"),
("Emmanuel","male"),
("Erasmus","male"),
("Eric","male"),
("Erica","female"),
("Erich","male"),
("Erin","female"),
("Ethan","male"),
("Eugenia","female"),
("Evan","male"),
("Evangeline","female"),
("Eve","female"),
("Evelyn","female"),
("Ezekiel","male"),
("Ezra","male"),
("Faith","female"),
("Fallon","female"),
("Farrah","female"),
("Fatima","female"),
("Fay","female"),
("Felicia","female"),
("Felix","male"),
("Ferdinand","male"),
("Ferris","male"),
("Finn","male"),
("Fiona","female"),
("Fitzgerald","male"),
("Flavia","female"),
("Fletcher","male"),
("Fleur","female"),
("Florence","female"),
("Flynn","male"),
("Forrest","male"),
("Frances","female"),
("Francesca","female"),
("Francis","male"),
("Fredericka","female"),
("Freya","female"),
("Fritz","male"),
("Fuller","male"),
("Fulton","male"),
("Gabriel","male"),
("Gage","male"),
("Gail","female"),
("Galena","female"),
("Galvin","male"),
("Gannon","male"),
("Gareth","male"),
("Garrett","male"),
("Garrison","male"),
("Garth","male"),
("Gary","male"),
("Gavin","male"),
("Gay","female"),
("Gemma","female"),
("Genevieve","female"),
("Geoffrey","male"),
("George","male"),
("Georgia","female"),
("Geraldine","female"),
("Germaine","female"),
("Germane","female"),
("Giacomo","male"),
("Gil","male"),
("Gillian","female"),
("Ginger","female"),
("Gisela","female"),
("Giselle","female"),
("Glenna","female"),
("Gloria","female"),
("Grace","female"),
("Grady","male"),
("Graham","male"),
("Graiden","male"),
("Grant","male"),
("Gray","male"),
("Gregory","male"),
("Gretchen","female"),
("Griffin","male"),
("Griffith","male"),
("Guinevere","female"),
("Guy","male"),
("Gwendolyn","female"),
("Hadassah","female"),
("Hadley","female"),
("Hakeem","male"),
("Halee","female"),
("Haley","female"),
("Hall","male"),
("Halla","female"),
("Hamilton","male"),
("Hamish","male"),
("Hammett","male"),
("Hanae","female"),
("Hanna","female"),
("Hannah","female"),
("Harding","male"),
("Harlan","male"),
("Harper","male"),
("Harriet","female"),
("Harrison","male"),
("Hasad","male"),
("Hashim","male"),
("Haviva","female"),
("Hayden","male"),
("Hayes","male"),
("Hayfa","female"),
("Hayley","female"),
("Heather","female"),
("Hector","male"),
("Hedda","female"),
("Hedley","male"),
("Hedwig","female"),
("Hedy","female"),
("Heidi","female"),
("Helen","female"),
("Henry","male"),
("Herman","male"),
("Hermione","female"),
("Herrod","male"),
("Hilary","female"),
("Hilda","female"),
("Hilel","male"),
("Hillary","female"),
("Hiram","male"),
("Hiroko","female"),
("Hollee","female"),
("Holly","female"),
("Holmes","male"),
("Honorato","male"),
("Hop","male"),
("Hope","female"),
("Howard","male"),
("Hoyt","male"),
("Hu","male"),
("Hunter","male"),
("Hyacinth","female"),
("Hyatt","male"),
("Ian","male"),
("Idola","female"),
("Idona","female"),
("Ifeoma","female"),
("Ignacia","female"),
("Ignatius","male"),
("Igor","male"),
("Ila","female"),
("Iliana","female"),
("Illana","female"),
("Illiana","female"),
("Ima","female"),
("Imani","female"),
("Imelda","female"),
("Imogene","female"),
("Ina","female"),
("India","female"),
("Indigo","female"),
("Indira","female"),
("Inez","female"),
("Inga","female"),
("Ingrid","female"),
("Iola","female"),
("Iona","female"),
("Ira","male"),
("Irene","female"),
("Iris","female"),
("Irma","female"),
("Isaac","male"),
("Isabella","female"),
("Isabelle","female"),
("Isadora","female"),
("Isaiah","male"),
("Ishmael","male"),
("Ivan","male"),
("Ivana","female"),
("Ivor","male"),
("Ivory","female"),
("Ivy","female"),
("Jack","male"),
("Jackson","male"),
("Jacob","male"),
("Jada","female"),
("Jade","female"),
("Jaden","female"),
("Jael","female"),
("Jaime","female"),
("Jakeem","male"),
("Jamal","male"),
("Jamalia","female"),
("James","male"),
("Jameson","male"),
("Jana","female"),
("Jane","female"),
("Janna","female"),
("Jaquelyn","female"),
("Jared","male"),
("Jarrod","male"),
("Jasmine","female"),
("Jason","male"),
("Jasper","male"),
("Jayme","female"),
("Jeanette","female"),
("Jelani","male"),
("Jemima","female"),
("Jena","female"),
("Jenette","female"),
("Jenna","female"),
("Jennifer","female"),
("Jeremy","male"),
("Jermaine","male"),
("Jerome","male"),
("Jerry","male"),
("Jescie","female"),
("Jessamine","female"),
("Jesse","male"),
("Jessica","female"),
("Jillian","female"),
("Jin","male"),
("Joan","female"),
("Jocelyn","female"),
("Joel","male"),
("Joelle","female"),
("John","male"),
("Jolene","female"),
("Jolie","female"),
("Jonah","male"),
("Jonas","male"),
("Jordan","female"),
("Jordan","male"),
("Jorden","female"),
("Joseph","male"),
("Josephine","female"),
("Joshua","male"),
("Josiah","male"),
("Joy","female"),
("Judah","male"),
("Judith","female"),
("Julian","male"),
("Julie","female"),
("Juliet","female"),
("Justin","male"),
("Justina","female"),
("Justine","female"),
("Kadeem","male"),
("Kaden","both"),
("Kai","female"),
("Kaitlin","female"),
("Kalia","female"),
("Kamal","male"),
("Kameko","female"),
("Kane","male"),
("Kareem","male"),
("Karen","female"),
("Karina","female"),
("Karleigh","female"),
("Karly","female"),
("Karyn","female"),
("Kaseem","male"),
("Kasimir","male"),
("Kasper","male"),
("Katell","female"),
("Katelyn","female"),
("Kathleen","female"),
("Kato","male"),
("Kay","female"),
("Kaye","female"),
("Keane","male"),
("Keaton","male"),
("Keefe","male"),
("Keegan","male"),
("Keelie","female"),
("Keely","female"),
("Keiko","female"),
("Keith","male"),
("Kellie","female"),
("Kelly","female"),
("Kelly","male"),
("Kelsey","female"),
("Kelsie","female"),
("Kendall","both"),
("Kennan","male"),
("Kennedy","male"),
("Kenneth","male"),
("Kenyon","male"),
("Kermit","male"),
("Kerry","female"),
("Kessie","female"),
("Kevin","male"),
("Kevyn","female"),
("Kiara","female"),
("Kiayada","female"),
("Kibo","male"),
("Kieran","male"),
("Kim","female"),
("Kimberley","female"),
("Kimberly","female"),
("Kiona","female"),
("Kirby","female"),
("Kirestin","female"),
("Kirk","male"),
("Kirsten","female"),
("Kitra","female"),
("Knox","male"),
("Kristen","female"),
("Kuame","male"),
("Kyla","female"),
("Kylan","female"),
("Kyle","male"),
("Kylee","female"),
("Kylie","female"),
("Kylynn","female"),
("Kyra","female"),
("Lacey","female"),
("Lacota","female"),
("Lacy","female"),
("Lael","female"),
("Laith","male"),
("Lamar","male"),
("Lana","female"),
("Lance","male"),
("Lane","male"),
("Lani","female"),
("Lara","female"),
("Lareina","female"),
("Larissa","female"),
("Lars","male"),
("Latifah","female"),
("Laura","female"),
("Laurel","female"),
("Lavinia","female"),
("Lawrence","male"),
("Leah","female"),
("Leandra","female"),
("Lee","female"),
("Lee","male"),
("Leigh","female"),
("Leila","female"),
("Leilani","female"),
("Len","male"),
("Lenore","female"),
("Leo","male"),
("Leonard","male"),
("Leroy","male"),
("Lesley","female"),
("Leslie","female"),
("Lester","male"),
("Lev","male"),
("Levi","male"),
("Lewis","male"),
("Libby","female"),
("Liberty","female"),
("Lila","female"),
("Lilah","female"),
("Lillian","female"),
("Lillith","female"),
("Linda","female"),
("Linus","male"),
("Lionel","male"),
("Lisandra","female"),
("Logan","male"),
("Lois","female"),
("Louis","male"),
("Lucas","male"),
("Lucian","male"),
("Lucius","male"),
("Lucy","female"),
("Luke","male"),
("Lunea","female"),
("Lydia","female"),
("Lyle","male"),
("Lynn","female"),
("Lysandra","female"),
("MacKensie","female"),
("MacKenzie","female"),
("Macaulay","male"),
("Macey","female"),
("Macon","male"),
("Macy","female"),
("Madaline","female"),
("Madeline","female"),
("Madeson","female"),
("Madison","female"),
("Madonna","female"),
("Magee","male"),
("Maggie","female"),
("Maggy","female"),
("Maia","female"),
("Maile","female"),
("Maisie","female"),
("Maite","female"),
("Malachi","male"),
("Malcolm","male"),
("Malik","male"),
("Mallory","female"),
("Mannix","male"),
("Mara","female"),
("Marah","female"),
("Marcia","female"),
("Margaret","female"),
("Mari","female"),
("Mariam","female"),
("Mariko","female"),
("Maris","female"),
("Mark","male"),
("Marny","female"),
("Marsden","male"),
("Marshall","male"),
("Martena","female"),
("Martha","female"),
("Martin","male"),
("Martina","female"),
("Marvin","male"),
("Mary","female"),
("Maryam","female"),
("Mason","male"),
("Matthew","male"),
("Maxine","female"),
("Maxwell","male"),
("May","female"),
("Maya","female"),
("McKenzie","female"),
("Mechelle","female"),
("Medge","female"),
("Megan","female"),
("Meghan","female"),
("Melanie","female"),
("Melinda","female"),
("Melissa","female"),
("Melodie","female"),
("Melvin","male"),
("Melyssa","female"),
("Mercedes","female"),
("Meredith","female"),
("Merrill","male"),
("Merritt","male"),
("Mia","female"),
("Micah","male"),
("Michael","male"),
("Michelle","female"),
("Mikayla","female"),
("Minerva","female"),
("Mira","female"),
("Miranda","female"),
("Miriam","female"),
("Moana","female"),
("Mohammad","male"),
("Mollie","female"),
("Molly","female"),
("Mona","female"),
("Montana","female"),
("Morgan","female"),
("Moses","male"),
("Mufutau","male"),
("Murphy","male"),
("Myles","male"),
("Myra","female"),
("Nadine","female"),
("Naida","female"),
("Naomi","female"),
("Nash","male"),
("Nasim","male"),
("Natalie","female"),
("Nathan","male"),
("Nathaniel","male"),
("Nayda","female"),
("Nehru","male"),
("Neil","male"),
("Nell","female"),
("Nelle","female"),
("Nerea","female"),
("Nero","male"),
("Nevada","female"),
("Neve","female"),
("Neville","male"),
("Nicholas","male"),
("Nichole","female"),
("Nicole","female"),
("Nigel","male"),
("Nina","female"),
("Nissim","male"),
("Nita","female"),
("Noah","male"),
("Noble","male"),
("Noel","female"),
("Noelani","female"),
("Noelle","female"),
("Nola","female"),
("Nolan","male"),
("Nomlanga","female"),
("Nora","female"),
("Norman","male"),
("Nyssa","female"),
("Ocean","female"),
("Octavia","female"),
("Octavius","male"),
("Odessa","female"),
("Odette","female"),
("Odysseus","male"),
("Oleg","male"),
("Olga","female"),
("Oliver","male"),
("Olivia","female"),
("Olympia","female"),
("Omar","male"),
("Oprah","female"),
("Ora","female"),
("Oren","male"),
("Ori","female"),
("Orla","female"),
("Orlando","male"),
("Orli","female"),
("Orson","male"),
("Oscar","male"),
("Otto","male"),
("Owen","male"),
("Paki","male"),
("Palmer","male"),
("Paloma","female"),
("Pamela","female"),
("Pandora","female"),
("Pascale","female"),
("Patience","female"),
("Patricia","female"),
("Patrick","male"),
("Paul","male"),
("Paula","female"),
("Pearl","female"),
("Penelope","female"),
("Perry","male"),
("Peter","male"),
("Petra","female"),
("Phelan","male"),
("Philip","male"),
("Phillip","male"),
("Phoebe","female"),
("Phyllis","female"),
("Piper","female"),
("Plato","male"),
("Porter","male"),
("Portia","female"),
("Prescott","male"),
("Preston","male"),
("Price","male"),
("Priscilla","female"),
("Quail","female"),
("Quamar","male"),
("Quemby","female"),
("Quentin","male"),
("Quin","female"),
("Quincy","both"),
("Quinlan","male"),
("Quinn","female"),
("Quinn","male"),
("Quintessa","female"),
("Quon","female"),
("Quyn","female"),
("Quynn","female"),
("Rachel","female"),
("Rae","female"),
("Rafael","male"),
("Rahim","male"),
("Raja","male"),
("Rajah","male"),
("Ralph","male"),
("Rama","female"),
("Ramona","female"),
("Rana","female"),
("Randall","male"),
("Raphael","male"),
("Rashad","male"),
("Raven","female"),
("Ray","male"),
("Raya","female"),
("Raymond","male"),
("Reagan","female"),
("Rebecca","female"),
("Rebekah","female"),
("Reece","male"),
("Reed","male"),
("Reese","male"),
("Regan","female"),
("Regina","female"),
("Remedios","female"),
("Renee","female"),
("Reuben","male"),
("Rhea","female"),
("Rhiannon","female"),
("Rhoda","female"),
("Rhona","female"),
("Rhonda","female"),
("Ria","female"),
("Richard","male"),
("Rigel","male"),
("Riley","female"),
("Rina","female"),
("Rinah","female"),
("Risa","female"),
("Roanna","female"),
("Roary","female"),
("Robert","male"),
("Robin","female"),
("Rogan","male"),
("Ronan","male"),
("Rooney","male"),
("Rosalyn","female"),
("Rose","female"),
("Ross","male"),
("Roth","male"),
("Rowan","female"),
("Ruby","female"),
("Rudyard","male"),
("Russell","male"),
("Ruth","female"),
("Ryan","male"),
("Ryder","male"),
("Rylee","female"),
("Sacha","female"),
("Sade","female"),
("Sage","female"),
("Salvador","male"),
("Samantha","female"),
("Samson","male"),
("Samuel","male"),
("Sandra","female"),
("Sara","female"),
("Sarah","female"),
("Sasha","female"),
("Savannah","female"),
("Sawyer","male"),
("Scarlet","female"),
("Scarlett","female"),
("Scott","male"),
("Sean","male"),
("Sebastian","male"),
("Selma","female"),
("September","female"),
("Serena","female"),
("Serina","female"),
("Seth","male"),
("Shad","male"),
("Shaeleigh","female"),
("Shafira","female"),
("Shaine","female"),
("Shana","female"),
("Shannon","female"),
("Sharon","female"),
("Shay","female"),
("Shea","female"),
("Sheila","female"),
("Shelby","female"),
("Shelley","female"),
("Shellie","female"),
("Shelly","female"),
("Shoshana","female"),
("Sierra","female"),
("Signe","female"),
("Sigourney","female"),
("Silas","male"),
("Simon","male"),
("Simone","female"),
("Skyler","female"),
("Slade","male"),
("Sloane","both"),
("Solomon","male"),
("Sonia","female"),
("Sonya","female"),
("Sophia","female"),
("Sopoline","female"),
("Stacey","female"),
("Stacy","female"),
("Steel","male"),
("Stella","female"),
("Stephanie","female"),
("Stephen","male"),
("Steven","male"),
("Stewart","male"),
("Stone","male"),
("Stuart","male"),
("Suki","female"),
("Summer","female"),
("Susan","female"),
("Sybil","female"),
("Sybill","female"),
("Sydnee","female"),
("Sydney","female"),
("Sylvester","male"),
("Sylvia","female"),
("TaShya","female"),
("Tad","male"),
("Tallulah","female"),
("Talon","male"),
("Tamara","female"),
("Tamekah","female"),
("Tana","female"),
("Tanek","male"),
("Tanisha","female"),
("Tanner","male"),
("Tanya","female"),
("Tara","female"),
("Tarik","male"),
("Tasha","female"),
("Tashya","female"),
("Tate","male"),
("Tatiana","female"),
("Tatum","female"),
("Tatyana","female"),
("Taylor","both"),
("Teagan","female"),
("Teegan","female"),
("Thaddeus","male"),
("Thane","male"),
("Theodore","male"),
("Thomas","male"),
("Thor","male"),
("Tiger","male"),
("Timon","male"),
("Timothy","male"),
("Tobias","male"),
("Todd","male"),
("Travis","male"),
("Trevor","male"),
("Troy","male"),
("Tucker","male"),
("Tyler","male"),
("Tyrone","male"),
("Ulla","female"),
("Ulric","male"),
("Ulysses","male"),
("Uma","female"),
("Unity","female"),
("Upton","male"),
("Uriah","male"),
("Uriel","male"),
("Urielle","female"),
("Ursa","female"),
("Ursula","female"),
("Uta","female"),
("Valentine","male"),
("Vance","male"),
("Vanna","female"),
("Vaughan","male"),
("Veda","female"),
("Velma","female"),
("Venus","female"),
("Vera","female"),
("Vernon","male"),
("Veronica","female"),
("Victor","male"),
("Victoria","female"),
("Vielka","female"),
("Vincent","male"),
("Violet","female"),
("Virginia","female"),
("Vivian","female"),
("Vivien","female"),
("Vladimir","male"),
("Wade","male"),
("Walker","male"),
("Wallace","male"),
("Walter","male"),
("Wanda","female"),
("Wang","male"),
("Warren","male"),
("Wayne","male"),
("Wendy","female"),
("Wesley","male"),
("Whilemina","female"),
("Whitney","female"),
("Whoopi","female"),
("Willa","female"),
("William","male"),
("Willow","female"),
("Wilma","female"),
("Wing","male"),
("Winifred","female"),
("Winter","female"),
("Wyatt","male"),
("Wylie","male"),
("Wynne","female"),
("Wynter","female"),
("Wyoming","female"),
("Xander","male"),
("Xandra","female"),
("Xantha","female"),
("Xanthus","male"),
("Xavier","male"),
("Xaviera","female"),
("Xena","female"),
("Xenos","male"),
("Xerxes","both"),
("Xyla","female"),
("Yael","female"),
("Yardley","male"),
("Yasir","male"),
("Yen","female"),
("Yeo","female"),
("Yetta","female"),
("Yoko","female"),
("Yolanda","female"),
("Yoshi","female"),
("Yoshio","male"),
("Yuli","male"),
("Yuri","female"),
("Yvette","female"),
("Yvonne","female"),
("Zachary","male"),
("Zachery","male"),
("Zahir","male"),
("Zane","male"),
("Zelda","female"),
("Zelenia","female"),
("Zena","female"),
("Zenaida","female"),
("Zenia","female"),
("Zeph","male"),
("Zephania","male"),
("Zephr","female"),
("Zeus","male"),
("Zia","female"),
("Zoe","female"),
("Zorita","female"),
("acqueline","female")
]

provinces = [
("Alberta","AB"),
("British Columbia","BC"),
("Manitoba","MB"),
("New Brunswick","NB"),
("Newfoundland and Labrador","NL"),
("Northwest Territories","NT"),
("Nova Scotia","NS"),
("Nunavut","NU"),
("Ontario","ON"),
("Prince Edward Island","PE"),
("Quebec","QC"),
("Saskatchewan","SK"),
("Yukon","YT")
]

provinces_netherlands = [
("Drenthe","Dr."),
("Flevoland","Fl."),
("Friesland","Fr."),
("Gelderland","Gld."),
("Groningen","Gr."),
("Limburg","L."),
("Noord Brabant","N.-Br."),
("Noord Holland","N.-H."),
("Overijssel","Ov."),
("Zuid Holland","Z.-H."),
("Utrecht","U."),
("Zeeland","Zld.")
]

states = [

("Alabama","AL"),
("Alaska","AK"),
("Arizona","AZ"),
("Arkansas","AK"),
("California","CA"),
("Colorado","CO"),
("Connecticut","CT"),
("Delaware","DE"),
("District of Columbia","DC"),
("Florida","FL"),
("Georgia","GA"),
("Hawaii","HI"),
("Idaho","ID"),
("Illinois","IL"),
("Indiana","IN"),
("Iowa","IA"),
("Kansas","KS"),
("Kentucky","KY"),
("Louisiana","LA"),
("Maine","ME"),
("Maryland","MD"),
("Massachusetts","MA"),
("Michigan","MI"),
("Minnesota","MN"),
("Mississippi","MS"),
("Missouri","MO"),
("Montana","MT"),
("Nebraska","NE"),
("Nevada","NV"),
("New Hampshire","NH"),
("New Jersey","NJ"),
("New Mexico","NM"),
("New York","NY"),
("North Carolina","NC"),
("North Dakota","ND"),
("Ohio","OH"),
("Oklahoma","OK"),
("Oregon","OR"),
("Pennsylvania","PA"),
("Rhode Island","RI"),
("South Carolina","SC"),
("South Dakota","SD"),
("Tennessee","TN"),
("Texas","TX"),
("Utah","UT"),
("Vermont","VT"),
("Virginia","VA"),
("Washington","WA"),
("West Virginia","WV"),
("Wisconsin","WI"),
("Wyoming","WY")
]

surnames = [
"Abbott",
"Acevedo",
"Acosta",
"Adams",
"Adkins",
"Aguilar",
"Aguirre",
"Albert",
"Alexander",
"Alford",
"Allen",
"Allison",
"Alston",
"Alvarado",
"Alvarez",
"Anderson",
"Andrews",
"Anthony",
"Armstrong",
"Arnold",
"Ashley",
"Atkins",
"Atkinson",
"Austin",
"Avery",
"Avila",
"Ayala",
"Ayers",
"Bailey",
"Baird",
"Baker",
"Baldwin",
"Ball",
"Ballard",
"Banks",
"Barber",
"Barker",
"Barlow",
"Barnes",
"Barnett",
"Barr",
"Barrera",
"Barrett",
"Barron",
"Barry",
"Bartlett",
"Barton",
"Bass",
"Bates",
"Battle",
"Bauer",
"Baxter",
"Beach",
"Bean",
"Beard",
"Beasley",
"Beck",
"Becker",
"Bell",
"Bender",
"Benjamin",
"Bennett",
"Benson",
"Bentley",
"Benton",
"Berg",
"Berger",
"Bernard",
"Berry",
"Best",
"Bird",
"Bishop",
"Black",
"Blackburn",
"Blackwell",
"Blair",
"Blake",
"Blanchard",
"Blankenship",
"Blevins",
"Bolton",
"Bond",
"Bonner",
"Booker",
"Boone",
"Booth",
"Bowen",
"Bowers",
"Bowman",
"Boyd",
"Boyer",
"Boyle",
"Bradford",
"Bradley",
"Bradshaw",
"Brady",
"Branch",
"Bray",
"Brennan",
"Brewer",
"Bridges",
"Briggs",
"Bright",
"Britt",
"Brock",
"Brooks",
"Brown",
"Browning",
"Bruce",
"Bryan",
"Bryant",
"Buchanan",
"Buck",
"Buckley",
"Buckner",
"Bullock",
"Burch",
"Burgess",
"Burke",
"Burks",
"Burnett",
"Burns",
"Burris",
"Burt",
"Burton",
"Bush",
"Butler",
"Byers",
"Byrd",
"Cabrera",
"Cain",
"Calderon",
"Caldwell",
"Calhoun",
"Callahan",
"Camacho",
"Cameron",
"Campbell",
"Campos",
"Cannon",
"Cantrell",
"Cantu",
"Cardenas",
"Carey",
"Carlson",
"Carney",
"Carpenter",
"Carr",
"Carrillo",
"Carroll",
"Carson",
"Carter",
"Carver",
"Case",
"Casey",
"Cash",
"Castaneda",
"Castillo",
"Castro",
"Cervantes",
"Chambers",
"Chan",
"Chandler",
"Chaney",
"Chang",
"Chapman",
"Charles",
"Chase",
"Chavez",
"Chen",
"Cherry",
"Christensen",
"Christian",
"Church",
"Clark",
"Clarke",
"Clay",
"Clayton",
"Clements",
"Clemons",
"Cleveland",
"Cline",
"Cobb",
"Cochran",
"Coffey",
"Cohen",
"Cole",
"Coleman",
"Collier",
"Collins",
"Colon",
"Combs",
"Compton",
"Conley",
"Conner",
"Conrad",
"Contreras",
"Conway",
"Cook",
"Cooke",
"Cooley",
"Cooper",
"Copeland",
"Cortez",
"Cote",
"Cotton",
"Cox",
"Craft",
"Craig",
"Crane",
"Crawford",
"Crosby",
"Cross",
"Cruz",
"Cummings",
"Cunningham",
"Curry",
"Curtis",
"Dale",
"Dalton",
"Daniel",
"Daniels",
"Daugherty",
"Davenport",
"David",
"Davidson",
"Davis",
"Dawson",
"Day",
"Dean",
"Decker",
"Dejesus",
"Delacruz",
"Delaney",
"Deleon",
"Delgado",
"Dennis",
"Diaz",
"Dickerson",
"Dickson",
"Dillard",
"Dillon",
"Dixon",
"Dodson",
"Dominguez",
"Donaldson",
"Donovan",
"Dorsey",
"Dotson",
"Douglas",
"Downs",
"Doyle",
"Drake",
"Dudley",
"Duffy",
"Duke",
"Duncan",
"Dunlap",
"Dunn",
"Duran",
"Durham",
"Dyer",
"Eaton",
"Edwards",
"Elliott",
"Ellis",
"Ellison",
"Emerson",
"England",
"English",
"Erickson",
"Espinoza",
"Estes",
"Estrada",
"Evans",
"Everett",
"Ewing",
"Farley",
"Farmer",
"Farrell",
"Faulkner",
"Ferguson",
"Fernandez",
"Ferrell",
"Fields",
"Figueroa",
"Finch",
"Finley",
"Fischer",
"Fisher",
"Fitzgerald",
"Fitzpatrick",
"Fleming",
"Fletcher",
"Flores",
"Flowers",
"Floyd",
"Flynn",
"Foley",
"Forbes",
"Ford",
"Foreman",
"Foster",
"Fowler",
"Fox",
"Francis",
"Franco",
"Frank",
"Franklin",
"Franks",
"Frazier",
"Frederick",
"Freeman",
"French",
"Frost",
"Fry",
"Frye",
"Fuentes",
"Fuller",
"Fulton",
"Gaines",
"Gallagher",
"Gallegos",
"Galloway",
"Gamble",
"Garcia",
"Gardner",
"Garner",
"Garrett",
"Garrison",
"Garza",
"Gates",
"Gay",
"Gentry",
"George",
"Gibbs",
"Gibson",
"Gilbert",
"Giles",
"Gill",
"Gillespie",
"Gilliam",
"Gilmore",
"Glass",
"Glenn",
"Glover",
"Goff",
"Golden",
"Gomez",
"Gonzales",
"Gonzalez",
"Good",
"Goodman",
"Goodwin",
"Gordon",
"Gould",
"Graham",
"Grant",
"Graves",
"Gray",
"Green",
"Greene",
"Greer",
"Gregory",
"Griffin",
"Griffith",
"Grimes",
"Gross",
"Guerra",
"Guerrero",
"Guthrie",
"Gutierrez",
"Guy",
"Guzman",
"Hahn",
"Hale",
"Haley",
"Hall",
"Hamilton",
"Hammond",
"Hampton",
"Hancock",
"Haney",
"Hansen",
"Hanson",
"Hardin",
"Harding",
"Hardy",
"Harmon",
"Harper",
"Harrell",
"Harrington",
"Harris",
"Harrison",
"Hart",
"Hartman",
"Harvey",
"Hatfield",
"Hawkins",
"Hayden",
"Hayes",
"Haynes",
"Hays",
"Head",
"Heath",
"Hebert",
"Henderson",
"Hendricks",
"Hendrix",
"Henry",
"Hensley",
"Henson",
"Herman",
"Hernandez",
"Herrera",
"Herring",
"Hess",
"Hester",
"Hewitt",
"Hickman",
"Hicks",
"Higgins",
"Hill",
"Hines",
"Hinton",
"Hobbs",
"Hodge",
"Hodges",
"Hoffman",
"Hogan",
"Holcomb",
"Holden",
"Holder",
"Holland",
"Holloway",
"Holman",
"Holmes",
"Holt",
"Hood",
"Hooper",
"Hoover",
"Hopkins",
"Hopper",
"Horn",
"Horne",
"Horton",
"House",
"Houston",
"Howard",
"Howe",
"Howell",
"Hubbard",
"Huber",
"Hudson",
"Huff",
"Huffman",
"Hughes",
"Hull",
"Humphrey",
"Hunt",
"Hunter",
"Hurley",
"Hurst",
"Hutchinson",
"Hyde",
"Ingram",
"Irwin",
"Jackson",
"Jacobs",
"Jacobson",
"James",
"Jarvis",
"Jefferson",
"Jenkins",
"Jennings",
"Jensen",
"Jimenez",
"Johns",
"Johnson",
"Johnston",
"Jones",
"Jordan",
"Joseph",
"Joyce",
"Joyner",
"Juarez",
"Justice",
"Kane",
"Kaufman",
"Keith",
"Keller",
"Kelley",
"Kelly",
"Kemp",
"Kennedy",
"Kent",
"Kerr",
"Key",
"Kidd",
"Kim",
"King",
"Kinney",
"Kirby",
"Kirk",
"Kirkland",
"Klein",
"Kline",
"Knapp",
"Knight",
"Knowles",
"Knox",
"Koch",
"Kramer",
"Lamb",
"Lambert",
"Lancaster",
"Landry",
"Lane",
"Lang",
"Langley",
"Lara",
"Larsen",
"Larson",
"Lawrence",
"Lawson",
"Le",
"Leach",
"Leblanc",
"Lee",
"Leon",
"Leonard",
"Lester",
"Levine",
"Levy",
"Lewis",
"Lindsay",
"Lindsey",
"Little",
"Livingston",
"Lloyd",
"Logan",
"Long",
"Lopez",
"Lott",
"Love",
"Lowe",
"Lowery",
"Lucas",
"Luna",
"Lynch",
"Lynn",
"Lyons",
"Macdonald",
"Macias",
"Mack",
"Madden",
"Maddox",
"Maldonado",
"Malone",
"Mann",
"Manning",
"Marks",
"Marquez",
"Marsh",
"Marshall",
"Martin",
"Martinez",
"Mason",
"Massey",
"Mathews",
"Mathis",
"Matthews",
"Maxwell",
"May",
"Mayer",
"Maynard",
"Mayo",
"Mays",
"Mcbride",
"Mccall",
"Mccarthy",
"Mccarty",
"Mcclain",
"Mcclure",
"Mcconnell",
"Mccormick",
"Mccoy",
"Mccray",
"Mccullough",
"Mcdaniel",
"Mcdonald",
"Mcdowell",
"Mcfadden",
"Mcfarland",
"Mcgee",
"Mcgowan",
"Mcguire",
"Mcintosh",
"Mcintyre",
"Mckay",
"Mckee",
"Mckenzie",
"Mckinney",
"Mcknight",
"Mclaughlin",
"Mclean",
"Mcleod",
"Mcmahon",
"Mcmillan",
"Mcneil",
"Mcpherson",
"Meadows",
"Medina",
"Mejia",
"Melendez",
"Melton",
"Mendez",
"Mendoza",
"Mercado",
"Mercer",
"Merrill",
"Merritt",
"Meyer",
"Meyers",
"Michael",
"Middleton",
"Miles",
"Miller",
"Mills",
"Miranda",
"Mitchell",
"Molina",
"Monroe",
"Montgomery",
"Montoya",
"Moody",
"Moon",
"Mooney",
"Moore",
"Morales",
"Moran",
"Moreno",
"Morgan",
"Morin",
"Morris",
"Morrison",
"Morrow",
"Morse",
"Morton",
"Moses",
"Mosley",
"Moss",
"Mueller",
"Mullen",
"Mullins",
"Munoz",
"Murphy",
"Murray",
"Myers",
"Nash",
"Navarro",
"Neal",
"Nelson",
"Newman",
"Newton",
"Nguyen",
"Nichols",
"Nicholson",
"Nielsen",
"Nieves",
"Nixon",
"Noble",
"Noel",
"Nolan",
"Norman",
"Norris",
"Norton",
"Nunez",
"Obrien",
"Ochoa",
"Oconnor",
"Odom",
"Odonnell",
"Oliver",
"Olsen",
"Olson",
"Oneal",
"Oneil",
"Oneill",
"Orr",
"Ortega",
"Ortiz",
"Osborn",
"Osborne",
"Owen",
"Owens",
"Pace",
"Pacheco",
"Padilla",
"Page",
"Palmer",
"Park",
"Parker",
"Parks",
"Parrish",
"Parsons",
"Pate",
"Patel",
"Patrick",
"Patterson",
"Patton",
"Paul",
"Payne",
"Pearson",
"Peck",
"Pena",
"Pennington",
"Perez",
"Perkins",
"Perry",
"Peters",
"Petersen",
"Peterson",
"Petty",
"Phelps",
"Phillips",
"Pickett",
"Pierce",
"Pittman",
"Pitts",
"Pollard",
"Poole",
"Pope",
"Porter",
"Potter",
"Potts",
"Powell",
"Powers",
"Pratt",
"Preston",
"Price",
"Prince",
"Pruitt",
"Puckett",
"Pugh",
"Quinn",
"Ramirez",
"Ramos",
"Ramsey",
"Randall",
"Randolph",
"Rasmussen",
"Ratliff",
"Ray",
"Raymond",
"Reed",
"Reese",
"Reeves",
"Reid",
"Reilly",
"Reyes",
"Reynolds",
"Rhodes",
"Rice",
"Rich",
"Richard",
"Richards",
"Richardson",
"Richmond",
"Riddle",
"Riggs",
"Riley",
"Rios",
"Rivas",
"Rivera",
"Rivers",
"Roach",
"Robbins",
"Roberson",
"Roberts",
"Robertson",
"Robinson",
"Robles",
"Rocha",
"Rodgers",
"Rodriguez",
"Rodriquez",
"Rogers",
"Rojas",
"Rollins",
"Roman",
"Romero",
"Rosa",
"Rosales",
"Rosario",
"Rose",
"Ross",
"Roth",
"Rowe",
"Rowland",
"Roy",
"Ruiz",
"Rush",
"Russell",
"Russo",
"Rutledge",
"Ryan",
"Salas",
"Salazar",
"Salinas",
"Sampson",
"Sanchez",
"Sanders",
"Sandoval",
"Sanford",
"Santana",
"Santiago",
"Santos",
"Sargent",
"Saunders",
"Savage",
"Sawyer",
"Schmidt",
"Schneider",
"Schroeder",
"Schultz",
"Schwartz",
"Scott",
"Sears",
"Sellers",
"Serrano",
"Sexton",
"Shaffer",
"Shannon",
"Sharp",
"Sharpe",
"Shaw",
"Shelton",
"Shepard",
"Shepherd",
"Sheppard",
"Sherman",
"Shields",
"Short",
"Silva",
"Simmons",
"Simon",
"Simpson",
"Sims",
"Singleton",
"Skinner",
"Slater",
"Sloan",
"Small",
"Smith",
"Snider",
"Snow",
"Snyder",
"Solis",
"Solomon",
"Sosa",
"Soto",
"Sparks",
"Spears",
"Spence",
"Spencer",
"Stafford",
"Stanley",
"Stanton",
"Stark",
"Steele",
"Stein",
"Stephens",
"Stephenson",
"Stevens",
"Stevenson",
"Stewart",
"Stokes",
"Stone",
"Stout",
"Strickland",
"Strong",
"Stuart",
"Suarez",
"Sullivan",
"Summers",
"Sutton",
"Swanson",
"Sweeney",
"Sweet",
"Sykes",
"Talley",
"Tanner",
"Tate",
"Taylor",
"Terrell",
"Terry",
"Thomas",
"Thompson",
"Thornton",
"Tillman",
"Todd",
"Torres",
"Townsend",
"Tran",
"Travis",
"Trevino",
"Trujillo",
"Tucker",
"Turner",
"Tyler",
"Tyson",
"Underwood",
"Valdez",
"Valencia",
"Valentine",
"Valenzuela",
"Vance",
"Vang",
"Vargas",
"Vasquez",
"Vaughan",
"Vaughn",
"Vazquez",
"Vega",
"Velasquez",
"Velazquez",
"Velez",
"Villarreal",
"Vincent",
"Vinson",
"Wade",
"Wagner",
"Walker",
"Wall",
"Wallace",
"Waller",
"Walls",
"Walsh",
"Walter",
"Walters",
"Walton",
"Ward",
"Ware",
"Warner",
"Warren",
"Washington",
"Waters",
"Watkins",
"Watson",
"Watts",
"Weaver",
"Webb",
"Weber",
"Webster",
"Weeks",
"Weiss",
"Welch",
"Wells",
"West",
"Wheeler",
"Whitaker",
"White",
"Whitehead",
"Whitfield",
"Whitley",
"Whitney",
"Wiggins",
"Wilcox",
"Wilder",
"Wiley",
"Wilkerson",
"Wilkins",
"Wilkinson",
"William",
"Williams",
"Williamson",
"Willis",
"Wilson",
"Winters",
"Wise",
"Witt",
"Wolf",
"Wolfe",
"Wong",
"Wood",
"Woodard",
"Woods",
"Woodward",
"Wooten",
"Workman",
"Wright",
"Wyatt",
"Wynn",
"Yang",
"Yates",
"York",
"Young",
"Zamora",
"Zimmerman"
]

from random import sample
cities = sample(cities, 1000)

def gen_voter(size):
	from random import choice, randrange
	cur_dni = 10000000
	while size:
		size-=1
		cur_dni += randrange(1,20)
		yield [cur_dni,\
				choice(first_names)[0]+" "+choice(surnames),\
				randrange(1000,9999),\
				choice(counties)[0],\
				choice(cities)]
			
def gen_district(size):
	from random import choice, randrange
	for i in range(size): yield [choice(cities)]
			
def gen_file(fname, list):
	import csv
	dialect = csv.Dialect
	dialect.lineterminator = '\n'
	csvout = csv.writer(open(fname, mode='w'), delimiter=',', dialect=dialect, quoting=csv.QUOTE_NONE)
	for row in list: csvout.writerow(row)
	
voters = [v for v in gen_voter(50000)]

districts = set()
for v in voters: districts.add((v[4],))

from random import randrange, sample, choice
charges = []
for d in districts:
	newc = ["Intendente de %s"%d[0]]
	for i in range(1,randrange(1,8)): newc += ["Concejal de %s Nro %d"%(d[0],i)]
	charges.append(newc)
provinces = {}
distlist = list(districts)
useddists = 0
for i in range(1,201):
	newc = ["Gobernador prov nro %d"%i, "ViceGobernador prov Nro %d"%i]
	charges.append(newc)
	n = choice([4,4,5,5,5,5])
	if i == 200: n = len(distlist)-useddists
	provinces[i] = [a[0] for a in distlist[useddists: useddists+n]] #n dist por provincia
	useddists += n
#~ print len(distlist)
#~ print (i-1)*5
#~ print provinces[200]
countries = {}
for i in range(1,21):
	newc = ["Presidente Nro %d"%i, "VicePresidente Nro %d"%i]
	charges.append(newc)
	countries[i] = [a[0] for a in distlist[(i-1)*50: (i-1)*50+50]] #50 dist por pais

elections = []
for d in districts:
	elections.append((randrange(10,31), randrange(10,13), 2011, "Intendente de %s"%d[0], d[0]))
for i in range(1,201):
	#~ print (randrange(1,31), randrange(1,13), 2011, "Gobernador provincia nro %d"%i)+tuple(provinces[i])
	#~ exit(0)
	provinces[i].sort()
	elections.append((randrange(10,31), randrange(10,13), 2011, "Gobernador prov nro %d"%i)+tuple(provinces[i]))
for i in range(1,21):
	countries[i].sort()
	elections.append((randrange(10,31), randrange(10,13), 2011, "Presidente Nro %d"%i)+tuple(countries[i]))

def electionscmp(a,b):
	return cmp(a[4:],b[4:])
elections.sort(electionscmp)


elist = []
for e in elections:
	for i in range(1, randrange(2,6)):
		elist.append((e[0],e[1],e[2],e[3],"Lista %d"%i)+tuple(e[4:]))
#~ print elist

simple_elist = [a[:5] for a in elist]

import sys
candidates = []
selected_dnis = set()
for el in elist:
	sys.stdout.write('.')
	sys.stdout.flush()
	okdists = el[5:]
	tries = 10000
	while tries:
		tries -= 1
		cand = choice(voters)
		if cand[0] in selected_dnis or cand[4] not in okdists: continue
		break
	if not tries:
		print "No se genero candidato para %s"%(str(okdists))
		print el
	candidates.append((el[4],el[0],el[1],el[2],cand[0],el[3]))

gen_file("padron.txt", voters)
gen_file("districts.txt", districts)
gen_file("charges.txt", charges)
gen_file("elections.txt", elections)
gen_file("electionList.txt", simple_elist)
gen_file("candidates.txt", candidates)

#fields = [cities, counties, countries, first_names, provinces, provinces_netherlands, states, surnames]

